export const pokemonTypeColors: any = {
	normal: { color: '#A0A29F' },
	fire: { color: '#FBA54C' },
	water: { color: '#539DDF' },
	electric: { color: '#F2D94E' },
	grass: { color: '#5FBD58' },
	ice: { color: '#75D0C1' },
	ground: { color: '#DA7C4D' },
	flying: { color: '#A1BBEC' },
	ghost: { color: '#5F6DBC' },
	rock: { color: '#C9BB8A' },
	fighting: { color: '#D3425F' },
	poison: { color: '#B763CF' },
	psychic: { color: '#FA8581' },
	bug: { color: '#92BC2C' },
	dark: { color: '#595761' },
	steel: { color: '#5695A3' },
	dragon: { color: '#0C69C8' },
	fairy: { color: '#EE90E6' }
}
